name: Frontend Cloud Run Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build
        env:
          IMAGE_NAME: frontend
          PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
          GCR_REPO_NAME: ${{ vars.GCR_REPO_NAME }}
        run: |-
          docker build --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }}  -t us-central1-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:latest -f frontend/Dockerfile frontend/.
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$GCR_REPO_NAME/$IMAGE_NAME:latest

      - name: Deploy to cloud run
        run: |
          gcloud run deploy projectflow-fe-new \
            --image us-central1-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCR_REPO_NAME }}/frontend:latest \
            --platform managed \
            --port=80 \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "VITE_API_URL=${{secrets.VITE_API_URL}}"
